SELECT SUM(TOTAL_AMOUNT) AS TOTAL_SALES
FROM DBT_DEV.MART_AI_DASHBOARD;

SELECT ORDER_ID, TOTAL_AMOUNT
FROM DBT_DEV.MART_AI_DASHBOARD;

SELECT CUSTOMER_NAME,
       SUM(TOTAL_AMOUNT) AS TOTAL_SPEND
FROM DBT_DEV.MART_AI_DASHBOARD
GROUP BY CUSTOMER_NAME
ORDER BY TOTAL_SPEND DESC
LIMIT 1;

SELECT CITY,
       SUM(TOTAL_AMOUNT) AS CITY_SALES
FROM DBT_DEV.MART_AI_DASHBOARD
GROUP BY CITY
ORDER BY CITY_SALES DESC;

SELECT PRODUCT_NAME,
       SUM(TOTAL_AMOUNT) AS PRODUCT_SALES
FROM DBT_DEV.MART_AI_DASHBOARD
GROUP BY PRODUCT_NAME
ORDER BY PRODUCT_SALES DESC;

SELECT COUNT(*) AS COMPLETED_ORDERS
FROM DBT_DEV.MART_AI_DASHBOARD
WHERE PAYMENT_STATUS = 'Completed';