version: 2

sources:

  - name: ecommerce

    database: ECOMMERCE_DB

    schema: PUBLIC

    tables:

      - name: CUSTOMER_REVENUE_V2
      - name: PRODUCT_SALES_V2
      - name: DAILY_REVENUE_V2
      - name: SALES_ANALYTICS