use database ECOMMERCE_DB;

select * from CUSTOMER_REVENUE_V2;
select * from  PRODUCT_SALES_V2;
select * from  DAILY_REVENUE_V2;

SELECT *
FROM dbt_dev.MART_DASHBOARD
LIMIT 2;


SELECT *
FROM DBT_DEV.DIM_CUSTOMER
LIMIT 4;

SELECT *
FROM DBT_DEV.DIM_PRODUCT
LIMIT 4;

SELECT *
FROM DBT_DEV.FCT_REVENUE
LIMIT 4;


-- ai mart dashboard
CREATE OR REPLACE TABLE SALES_ANALYTICS (
    ORDER_ID NUMBER,
    ORDER_DATE DATE,
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME STRING,
    CITY STRING,
    COUNTRY STRING,
    PRODUCT_ID STRING,
    PRODUCT_NAME STRING,
    CATEGORY STRING,
    QUANTITY NUMBER,
    TOTAL_AMOUNT NUMBER(10,2),
    PAYMENT_METHOD STRING,
    PAYMENT_STATUS STRING
);

SHOW TABLES LIKE 'SALES_ANALYTICS';

SELECT *
FROM DBT_DEV.MART_AI_DASHBOARD
LIMIT 10;

select * from sales_analytics

SELECT COUNT(*)
FROM ECOMMERCE_DB.PUBLIC.SALES_ANALYTICS;