CREATE OR REPLACE TABLE SALES_ANALYTICS (
    ORDER_ID NUMBER,
    ORDER_DATE DATE,
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME STRING,
    CITY STRING,
    COUNTRY STRING,
    PRODUCT_ID STRING,
    PRODUCT_NAME STRING,
    CATEGORY STRING,
    QUANTITY NUMBER,
    TOTAL_AMOUNT NUMBER(10,2),
    PAYMENT_METHOD STRING,
    PAYMENT_STATUS STRING
);