version: 2

models:

  - name: stg_customer_revenue
    columns:
      - name: customer_id
        tests:
          - not_null

  - name: stg_product_sales
    columns:
      - name: product_id
        tests:
          - not_null

  - name: mart_dashboard
    columns:
      - name: total_revenue
        tests:
          - not_null